apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello-arc
  namespace: new
spec:
  releaseName: hello-arc-prod
  chart:
    git: https://github.com/ebizzity/arcgitopsdemo.git
    path: charts/hello-arc
    ref: master
  values:
    image:
      repository: liorkamrat/hello-arc
      tag: latest
    replicaCount: 1
    env:
      name: MESSAGE
      value: Gitops Demo!
